"""Inference model service configuration and parsing."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal
from urllib.parse import urlparse

from embodirun.model_services.providers import provider

from .server import ServerConfig, parse_server
from .transport import parse_transport_options
from .validation import (
    ConfigError,
    optional_string,
    reject_unknown,
    string,
)

_COMMON_FIELDS = {
    "backend",
    "provider",
    "transport",
    "type",
    "service",
    "lifecycle",
    "node",
    "environment",
    "python",
    "environment_index",
    "environment_packages",
    "server",
    "endpoint",
    "transport_options",
    # Managed providers commonly need a checkpoint path.  Providers may add
    # narrower options, but this common key keeps third-party descriptors
    # usable without changing the Host parser.
    "source",
}


@dataclass(frozen=True, slots=True)
class ModelConfig:
    model_id: str
    backend: str
    transport: str
    kind: str
    node: str | None
    environment: str | None
    python: str | None
    environment_index: str | None
    environment_packages: tuple[str, ...]
    server: ServerConfig | None
    options: dict[str, Any] = field(default_factory=dict, repr=False)
    transport_options: dict[str, Any] = field(default_factory=dict, repr=False)
    lifecycle: Literal["managed", "external"] = "managed"
    endpoint: str | None = None


def parse_model(model_id: str, value: dict[str, Any]) -> ModelConfig:
    context = f"models.{model_id}"
    legacy = {"comm_config", "client_comm_config", "server_node_id"} & value.keys()
    if legacy:
        raise ConfigError(
            f"{context}: {', '.join(sorted(legacy))} is now generated by Host; "
            "use model.server and runtime.inference_client instead"
        )
    transport = string(value, "transport", context)
    backend = value.get("backend", value.get("provider"))
    if not isinstance(backend, str) or not backend.strip():
        raise ConfigError(f"{context}.backend (or provider) must be a non-empty string")
    if "backend" in value and "provider" in value and value["backend"] != value["provider"]:
        raise ConfigError(f"{context}.backend and provider must match")
    service_value = value.get("service")
    lifecycle_value = value.get("lifecycle")
    if service_value is not None and lifecycle_value is not None and service_value != lifecycle_value:
        raise ConfigError(f"{context}.service and lifecycle must match")
    lifecycle = value.get("service", value.get("lifecycle", "managed"))
    if lifecycle not in {"managed", "external"}:
        raise ConfigError(f"{context}.service must be managed or external")
    endpoint = optional_string(value, "endpoint", context)
    try:
        selected_provider = provider(backend)
    except ValueError as error:
        raise ConfigError(f"{context}.backend: {error}") from error
    reject_unknown(
        value,
        _COMMON_FIELDS | set(selected_provider.allowed_options),
        context,
    )
    if not selected_provider.supports(transport):
        raise ConfigError(f"{context}.transport {transport!r} is not supported by provider {backend!r}")
    if not selected_provider.action_capable:
        raise ConfigError(f"{context}.backend {backend!r} has no action capability")
    if lifecycle == "managed" and selected_provider.managed_command is None:
        raise ConfigError(f"{context}.backend {backend!r} has no managed service descriptor")
    if (
        lifecycle == "managed"
        and selected_provider.requires_checkpoint
        and (not isinstance(value.get("source"), str) or not value["source"].strip())
    ):
        raise ConfigError(f"{context}.source is required for a managed service")
    if lifecycle == "external":
        try:
            parsed_endpoint = urlparse(endpoint or "")
            _ = parsed_endpoint.port
        except ValueError as error:
            raise ConfigError(f"{context}.endpoint is not a valid URL") from error
        if not parsed_endpoint.scheme or not parsed_endpoint.netloc or not parsed_endpoint.hostname:
            raise ConfigError(f"{context}.endpoint must be an absolute URL for an external service")
        if parsed_endpoint.query or parsed_endpoint.fragment:
            raise ConfigError(f"{context}.endpoint must not contain a query or fragment")
        if parsed_endpoint.username is not None or parsed_endpoint.password is not None:
            raise ConfigError(f"{context}.endpoint must not embed credentials; use the token option")
        if transport == "http" and parsed_endpoint.scheme not in {"http", "https"}:
            raise ConfigError(f"{context}.endpoint must use http or https for http transport")
        if transport == "wireless":
            raise ConfigError(f"{context}.external wireless services are unsupported; use an http endpoint")
        if any(
            name in value
            for name in {
                "source",
                "gpu",
                "environment_packages",
                "server",
                "node",
                "environment",
                "python",
                "environment_index",
                "adapter_config",
                "server_args",
                "server_executable",
                "pipeline",
                "pipeline_config",
            }
        ):
            raise ConfigError(
                f"{context}: external services cannot declare managed node, environment, checkpoint, or server fields"
            )
    elif endpoint is not None:
        raise ConfigError(f"{context}.endpoint is only valid for an external service")
    if "transport_options" in value and transport != "wireless":
        raise ConfigError(f"{context}.transport_options requires wireless transport")
    environment_packages = _environment_packages(value, context)
    environment_index = optional_string(value, "environment_index", context)
    if environment_index is not None and not environment_packages:
        raise ConfigError(f"{context}.environment_index requires environment_packages")
    server_value = value.get("server")
    server = parse_server(server_value, f"{context}.server") if server_value is not None else None
    if lifecycle == "managed" and server is None:
        raise ConfigError(f"{context}.server is required for a managed service")
    return ModelConfig(
        model_id=model_id,
        backend=backend,
        transport=transport,
        kind=string(value, "type", context),
        lifecycle=lifecycle,
        endpoint=endpoint,
        node=(string(value, "node", context) if lifecycle == "managed" or "node" in value else None),
        environment=optional_string(value, "environment", context),
        python=optional_string(value, "python", context),
        environment_index=environment_index,
        environment_packages=environment_packages,
        server=server,
        options=dict(value),
        transport_options=parse_transport_options(value.get("transport_options", {}), f"{context}.transport_options"),
    )


def _environment_packages(
    value: dict[str, Any],
    context: str,
) -> tuple[str, ...]:
    packages = value.get("environment_packages")
    if packages is None:
        return ()
    if not isinstance(packages, list) or not packages:
        raise ConfigError(f"{context}.environment_packages must be a non-empty list")
    result: list[str] = []
    for index, package in enumerate(packages):
        if not isinstance(package, str) or not package.strip() or package.startswith("-"):
            raise ConfigError(f"{context}.environment_packages[{index}] must be a package requirement")
        result.append(package)
    return tuple(result)


__all__ = ["ModelConfig"]
