"""LightNav-0 waypoint control for the XLeRobot omnidirectional base.

The package deliberately contains no SDK import or connection side effect.  A
backend is injected into :class:`LightNav0Controller`.
"""

from embodirun.robots.xlerobot.remote_client import (
    RemoteRobot,
    RemoteRobotError,
    build_remote_robot_from_env,
)

from .local_segment import (
    LocalSegmentBackend,
    LocalSegmentCollision,
    LocalSegmentConfig,
    LocalSegmentError,
    LocalSegmentExecutor,
    LocalSegmentFeedback,
    LocalSegmentFeedbackError,
    LocalSegmentFeedbackStale,
    LocalSegmentLeaseLost,
    LocalSegmentNotStationary,
    LocalSegmentOutputError,
    LocalSegmentStep,
    LocalSegmentTrajectory,
    select_unicycle_waypoint,
    waypoint_to_body_velocity,
)
from .teleop import (
    LocalizationStale,
    LocalizationUnavailable,
    TeleopLocalization,
    TeleopLocalizationProvider,
    XLeRobotFeedbackCached,
    XLeRobotStopUnconfirmed,
    XLeRobotTeleopBackend,
    XLeRobotTeleopCommandError,
    XLeRobotTeleopError,
    XLeRobotTeleopLocalSegmentBackend,
    XLeRobotTeleopRobot,
)
from .tracker import (
    BodyVelocity,
    Feedback,
    LightNav0Controller,
    LightNav0Error,
    LightNav0OutputError,
    LightNav0Tracker,
    LightNav0Trajectory,
    LightNav0Waypoint,
    Pose2D,
    TrackerConfig,
    TrackingDecision,
    XLeRobotBackend,
    parse_lightnav0_output,
    project_body_to_world,
    project_world_to_body,
)

__all__ = [
    "BodyVelocity",
    "Feedback",
    "LightNav0Controller",
    "LightNav0Error",
    "LightNav0OutputError",
    "LightNav0Tracker",
    "LightNav0Trajectory",
    "LightNav0Waypoint",
    "LocalSegmentBackend",
    "LocalSegmentCollision",
    "LocalSegmentConfig",
    "LocalSegmentError",
    "LocalSegmentExecutor",
    "LocalSegmentFeedback",
    "LocalSegmentFeedbackError",
    "LocalSegmentFeedbackStale",
    "LocalSegmentLeaseLost",
    "LocalSegmentNotStationary",
    "LocalSegmentOutputError",
    "LocalSegmentStep",
    "LocalSegmentTrajectory",
    "LocalizationStale",
    "LocalizationUnavailable",
    "Pose2D",
    "RemoteRobot",
    "RemoteRobotError",
    "TeleopLocalization",
    "TeleopLocalizationProvider",
    "TrackerConfig",
    "TrackingDecision",
    "XLeRobotBackend",
    "XLeRobotFeedbackCached",
    "XLeRobotStopUnconfirmed",
    "XLeRobotTeleopBackend",
    "XLeRobotTeleopCommandError",
    "XLeRobotTeleopError",
    "XLeRobotTeleopLocalSegmentBackend",
    "XLeRobotTeleopRobot",
    "build_remote_robot_from_env",
    "parse_lightnav0_output",
    "project_body_to_world",
    "project_world_to_body",
    "remote_client",
    "select_unicycle_waypoint",
    "waypoint_to_body_velocity",
]

from embodirun.robots.xlerobot import remote_client
